name = "cpp"
title = "cpp"

intersphinx = [
    "https://www.mongodb.com/docs/manual/objects.inv",
    "https://www.mongodb.com/docs/drivers/objects.inv",
    "https://www.mongodb.com/docs/atlas/objects.inv",
]

sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"
